# Generated by Django 6.0.6 on 2026-06-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathersearches',
            options={'ordering': ['-searched_at'], 'verbose_name_plural': 'Weather Searches'},
        ),
        migrations.RenameField(
            model_name='weathersearches',
            old_name='when_searched',
            new_name='searched_at',
        ),
        migrations.AddField(
            model_name='weathersearches',
            name='condition',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='weathersearches',
            name='feels_like',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weathersearches',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weathersearches',
            name='pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weathersearches',
            name='wind_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weathersearches',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
